### ISSUE TITLE
Problems getting data from stock antminer firmware on 0.57.x

### ISSUE THREAD

**Issue by martyfay1** [UpstreamData/pyasic#152]
**Describe the bug**
When trying to `get_data` from an Antminer (S19 XP) running stock firmware, it will return an error like : `Failed to call expected_hashrate on S19 XP (Stock): <ip> while getting data.`. This did not happen on 0.56, and when trying to `get_data` for the same IP on 0.56 returns all of the data as expected.

**Miner Information (If applicable):**
 - Manufacturer: Antminer
 - Type: S19 XP, (maybe more)
 - Firmware Type: stock

**Comment by b-rowan** [comment]
Should be fixed in 0.57.5.  I missed a spelling mistake that my ide didnt pick up (`.int()` instead of `.into()` for the new hashrate class)

Keep in mind that this update changes the way hashrate works, each hashrate item is not comprised of a `rate` and a `unit`.  In json/dict form, you can multiply the rate * the unit to get the number of hashes per second (H/s), and on the instance you can call `.into` with a hashrate unit to get the hashrate in any other compatible unit.  EG you could sum up the hashrates then `.into` them into PH/s for a larger farm, or get your hashrate as GH/s rather than the default TH/s, while it is still unit aware.
