### ISSUE TITLE
Why pyasic now don't return Unknow type miner but return None

### ISSUE THREAD

**Issue by Awote** [UpstreamData/pyasic#64]
I really can't remember then pyasic return class Unknow miner when i use function **pyasic.get_miner(ip)**.
Now this func return None then can't find miner. Is this okey or it's bug ?

**Comment by UpstreamData** [comment]
Yeah this is expected behavior.  I improved the `get_miner` function a while back, and it is much more robust in how it checks for miners now, but will return None of it can't find anything to verify that a device is a miner.  It will handle miners with unknown miner models with their base classes, E.G an unsupported BOS+ device would get the BOSMiner base class, which should still be relatively accurate.  Getting an UnknownMiner is still possible, but pyasic must first be certain there is a device there with port 4028 open that responds to RPC commands.

If you have a case where a miner is being missed, please open a separate issue and I can find a way to add it, but generally, returning None for "nothing there" seemed the most pythonic.
